import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../../app/app.dart';
import '../../../../core/theme/app_spacing.dart';
import '../../../../shared/widgets/app_button.dart';
import '../../../../shared/widgets/app_dropdown.dart';
import '../../../../shared/widgets/app_bottom_sheet_select.dart';
import '../../domain/models/job_request_model.dart';
import '../../data/repositories/firebase_job_repository_impl.dart';

class HireTutorScreen extends StatefulWidget {
  const HireTutorScreen({super.key});

  @override
  State<HireTutorScreen> createState() => _HireTutorScreenState();
}

class _HireTutorScreenState extends State<HireTutorScreen> {
  final _formKey = GlobalKey<FormState>();
  final _jobRepository = FirebaseJobRepositoryImpl();

  String? _selectedLevel;
  String? _selectedDistrict;
  String? _selectedArea;
  String _tuitionMode = 'Home Tuition';
  int _daysPerWeek = 5;
  double _salary = 5000;
  
  final List<String> _selectedSubjects = [];

  final List<String> _availableSubjects = [
    'Compulsory Math',
    'Optional Math',
    'Science',
    'English',
    'Nepali',
    'Accountancy',
    'Social Studies',
    'Physics',
    'Chemistry',
    'Computer Science',
  ];

  bool _isLoading = false;

  void _submitRequest() async {
    if (!(_formKey.currentState?.validate() ?? false)) return;
    if (_selectedSubjects.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select at least one subject.')));
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = AuthProviderInherited.of(context).user;
      if (user == null) throw Exception("User not logged in");

      final newJob = JobRequestModel(
        jobId: '', // Generated by Firestore
        studentId: user.id,
        studentName: user.fullName,
        level: _selectedLevel ?? 'Unknown',
        subjects: _selectedSubjects,
        district: _selectedDistrict ?? 'Kathmandu',
        area: _selectedArea ?? '',
        salaryNpr: _salary,
        tuitionMode: _tuitionMode,
        daysPerWeek: _daysPerWeek,
        createdAt: DateTime.now(),
      );

      await _jobRepository.createJobRequest(newJob);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Tutor request posted successfully!')));
        context.pop(); // Go back to dashboard
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: ${e.toString()}')));
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(title: const Text('Hire a Tutor')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppSpacing.lg),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  'Post your requirement',
                  style: theme.textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: AppSpacing.sm),
                Text(
                  'Fill in the details below to find the perfect tutor match.',
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: theme.colorScheme.onSurface.withValues(alpha: 0.7),
                  ),
                ),
                const SizedBox(height: AppSpacing.xl),

                // 1. Level / Grade
                AppBottomSheetSelect(
                  label: 'Student Level / Class',
                  hint: 'Select Grade or Level',
                  value: _selectedLevel,
                  options: const [
                    'Primary (Grade 1-5)',
                    'Middle (Grade 6-8)',
                    'Secondary (Grade 9-10)',
                    '+2 Science',
                    '+2 Management',
                    'Bachelor\'s Degree'
                  ],
                  onChanged: (v) => setState(() => _selectedLevel = v),
                ),
                if (_selectedLevel == null) 
                  Padding(
                    padding: const EdgeInsets.only(top: 4, left: 16),
                    child: Text('Required', style: TextStyle(color: theme.colorScheme.error, fontSize: 12)),
                  ),

                const SizedBox(height: AppSpacing.lg),

                // 2. Subjects (Chips)
                Text('Subjects Required', style: theme.textTheme.labelLarge),
                const SizedBox(height: AppSpacing.sm),
                Wrap(
                  spacing: 8.0,
                  runSpacing: 4.0,
                  children: _availableSubjects.map((subject) {
                    final isSelected = _selectedSubjects.contains(subject);
                    return FilterChip(
                      label: Text(subject),
                      selected: isSelected,
                      onSelected: (selected) {
                        setState(() {
                          if (selected) {
                            _selectedSubjects.add(subject);
                          } else {
                            _selectedSubjects.remove(subject);
                          }
                        });
                      },
                    );
                  }).toList(),
                ),

                const SizedBox(height: AppSpacing.lg),

                // 3. District & Area
                Row(
                  children: [
                    Expanded(
                      child: AppDropdown(
                        label: 'District',
                        hint: 'Select',
                        value: _selectedDistrict,
                        items: const ['Kathmandu', 'Lalitpur', 'Bhaktapur'],
                        onChanged: (v) => setState(() {
                          _selectedDistrict = v;
                          _selectedArea = null; // reset area when district changes
                        }),
                      ),
                    ),
                    const SizedBox(width: AppSpacing.md),
                    Expanded(
                      child: AppBottomSheetSelect(
                        label: 'Area/Location',
                        hint: 'Select',
                        value: _selectedArea,
                        options: _selectedDistrict == 'Lalitpur'
                            ? ['Patan', 'Jhamsikhel', 'Bhaisepati', 'Imadol', 'Kupondole']
                            : _selectedDistrict == 'Bhaktapur'
                                ? ['Suryabinayak', 'Thimi', 'Kamalbinayak', 'Balkot']
                                : ['Baneshwor', 'Koteshwor', 'Balaju', 'Chabahil', 'Maharajgunj'],
                        onChanged: (v) => setState(() => _selectedArea = v),
                      ),
                    ),
                  ],
                ),

                const SizedBox(height: AppSpacing.xl),

                // 4. Tuition Mode & Days
                Text('Tuition Preferences', style: theme.textTheme.labelLarge),
                const SizedBox(height: AppSpacing.sm),
                SegmentedButton<String>(
                  segments: const [
                    ButtonSegment(value: 'Home Tuition', label: Text('Home')),
                    ButtonSegment(value: "Tutor's Place", label: Text('Tutor\'s Place')),
                    ButtonSegment(value: 'Online', label: Text('Online')),
                  ],
                  selected: {_tuitionMode},
                  onSelectionChanged: (set) => setState(() => _tuitionMode = set.first),
                ),
                
                const SizedBox(height: AppSpacing.md),
                AppDropdown(
                  label: 'Days per Week',
                  value: _daysPerWeek.toString(),
                  items: const ['1', '2', '3', '4', '5', '6', '7'],
                  onChanged: (v) => setState(() => _daysPerWeek = int.parse(v!)),
                ),

                const SizedBox(height: AppSpacing.xl),

                // 5. Salary Budget
                Text('Monthly Budget: Rs. ${_salary.toInt()}', style: theme.textTheme.labelLarge),
                Slider(
                  value: _salary,
                  min: 2000,
                  max: 25000,
                  divisions: 46, // 25000-2000 = 23000 / 500 = 46
                  label: 'Rs. ${_salary.toInt()}',
                  onChanged: (v) => setState(() => _salary = v),
                ),

                const SizedBox(height: AppSpacing.xxl),
                AppButton(
                  text: 'Post Request',
                  isLoading: _isLoading,
                  onPressed: _submitRequest,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
