// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZno_Mc7zjiMD-QacS2L65QSoIUxF9ms8',
    appId: '1:239482583732:ios:ae3a45cca4a46f6706f5e1',
    messagingSenderId: '239482583732',
    projectId: 'tutormatee',
    storageBucket: 'tutormatee.firebasestorage.app',
    iosBundleId: 'com.example.tutormate',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-w7nF-0ZKUBXjLoIEGEBjrvExikBa6k',
    appId: '1:239482583732:web:2544ec5762eac61406f5e1',
    messagingSenderId: '239482583732',
    projectId: 'tutormatee',
    authDomain: 'tutormatee.firebaseapp.com',
    storageBucket: 'tutormatee.firebasestorage.app',
    measurementId: 'G-J3CY49S203',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxsFNspq4-7PZDqkt74zPX33PFXvItmw',
    appId: '1:239482583732:android:1bb48c0d23e3030b06f5e1',
    messagingSenderId: '239482583732',
    projectId: 'tutormatee',
    storageBucket: 'tutormatee.firebasestorage.app',
  );
}
